### ISSUE TITLE
Failure to Reconnect to Oracle 12c.

### ISSUE THREAD

**Issue by klfgit** [knex/knex#2514]
# Environment
node: v8.6.0
oracle db: 2.0.15
Knex version: 0.14.2
Database + version: oracle 12c
OS: REPL 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ Grimace1975 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

What I see: Knex does not reconnect after the db bounces.  
What I expect: Knex should reconnect after the db bounces.

2. Error message

> Error: ORA-03114: not connected to ORACLE

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

My test procedure:
1. Start the DB.
2. Run the code below.
3. Stop the DB.
4. Once I see the 'Error: ORA-03113: end-of-file on communication channel' error.
5. Wait a few seconds then restart the DB.  Once the DB is up I expect to start seeing the SYSDATE again.

```
'use strict';

var knex = require('knex')({
    client : 'oracledb',
    connection: {
        "user": "user",
        "password": "pwd",
        "database": "sid",
        "host": "host:port"
    },
    debug: false,
    pool: {
        "min": 0,
        "max": 3
    }
});

 function  exitIfDBIsDown() {
    knex.raw('select sysdate from dual').then(resp => {
       console.log(resp);
    }).catch(async err => {
        console.log(err);
    });
}

setInterval(exitIfDBIsDown, 2*1000);
```

example output: 

> [ { SYSDATE: 2018-02-27T02:09:24.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:25.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:27.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:29.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:31.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:33.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:35.000Z } ]
> [ { SYSDATE: 2018-02-27T02:09:37.000Z } ]
> Error: ORA-03113: end-of-file on communication channel
> Process ID: 461
> Session ID: 139 Serial number: 4295026557
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> Error: ORA-03114: not connected to ORACLE
> ....

I see the Error: ORA-03114: not connected to ORACLE for the rest of the life of the program. I know the db is running because I'm able to connect to it using sqlplus.  Also if I restart the app it connects and once again prints the sysdate. 

@atiertant

**Comment by elhigu** [comment]
please try again with 0.14.4. 0.14.2 was badly broken.

**Comment by klfgit** [comment]
@elhigu it's still broken in 0.14.4.  
Thanks in advance for working on an oracledb fix.

**Comment by klfgit** [comment]
Below is the stack for the error
```
Trace: Error: ORA-03114: not connected to ORACLE
    at knex.raw.then.catch.err (/IdeaProjects/attendance-resource/app/contest.js:22:17)
    at tryCatcher (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/IdeaProjects/attendance-resource/app/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by daveradical** [comment]
Hi @elhigu, is there any update on this? I see this issue on my project too.
Thanks for all the hard work!

**Comment by elhigu** [comment]
Nope, I still havent got time to even finish mssql.

**Comment by jfgodoy** [comment]
I having the same issue with oracle and the error `ORA-03114`.
This is what I discovered:
- knex destroy connections that has the flag `__knex__disposed` [/src/client.js#L261](https://github.com/tgriesser/knex/blob/8488e22abe8a6b33d835f69131b0da905b6eb783/src/client.js#L261)
- the oracle driver set this flag only for connection errors [/src/dialects/oracle/index.js#L148](https://github.com/tgriesser/knex/blob/bf1fa631183e143add6be2b35d5a9ee750ae78c8/src/dialects/oracle/index.js#L148)
- only `['ORA-12514', 'NJS-040', 'NJS-024', 'NJS-003', 'NJS-024']` are considered connections errors [/src/dialects/oracle/index.js#L18](https://github.com/tgriesser/knex/blob/bf1fa631183e143add6be2b35d5a9ee750ae78c8/src/dialects/oracle/index.js#L189)

The solution seems to be to add `ORA-03114` to the error connection list

**Comment by elhigu** [comment]
@jfgodoy thanks a lot, should be easy fix then 👍

**Comment by amirmehdizadeh** [comment]
I having the same issue with oracledb client.
If you restart Oracle database, the application can not reconnect to DB with error ORA-03114.
any plan to fix this?

**Comment by cemremengu** [comment]
@jfgodoy ```The solution seems to be to add ORA-03114 to the error connection list```

I think


@atiertant  Does the solution given by @jfgodoy solve the issue? If so is there a PR for it?

**Comment by atiertant** [comment]
@cemremengu did not have time to test but oracledb dialect inherit from oracle dialect.

**Comment by electrotype** [comment]
We have this issue, with Knex 0.14.3. What is currently the best way to workaround it until the PR is merged? Are knex versions below 0.14.2 work?

**Comment by elhigu** [comment]
@beltschatsar even that it helps, it doesn't sound like root cause for the problem that oracle is not reconnecting. I mean, knex shouldn't need to wait idletimeout evict connections from pool, whose sockets were closed.

**Comment by beltschatsar** [comment]
Totally Agree with you @elhigu . My comment was for a workaround.

**Comment by BaronMing1** [comment]
Had the same problem, and I solve it on a curious way, but I did it.
When I ask for my method getOracleClient, if I already have a connection at the beginning I was doing nothing. Now I test my Query. If I have a connection error like Ora-03114 or Ora-03135 I set my client to undefined and I ask for a new connection. That works.  Don't reset your client on some other errors because it won't works.

** My code is from typescript.

const knexClient: knex;

export async function getOracleClient(): Promise<knex> {
// If we lost the connection. We need to reset the client and get a new connection.
  // ONLY if we lost a connection. Because doing an Undefined, on other errors, will create other connection errors like Pool if full.
  // The best way to validate if the connection is OK, is just test a small query
if (knexClient) {
    await client
      .select(xxx)
      .from(xxx)
      .catch(async (err: any) => {
        if (err.errorNum === 3114 || err.errorNum === 3135) {
          // The only time we can get new connection is when error are from a lost connection : 3114 and 3135
        // By setting an undefined, it will enter in the other IF and get a new connection.
          knexClient= undefined;
        }
      });
  }
 if (!knexClient) {
    knexClient= knex(connectOptions);
  }
  return knexClient
}

 function  exitIfDBIsDown() {
    knex.raw('select sysdate from dual').then(resp => {
       console.log(resp);
    }).catch(async err => {
        console.log(err);
    });
}

public async findById(id: string): Promise<any> {
    
    try {
      const oracleConnection: knex = await getOracleClient();
      const result = await oracleConnection
        .select(xxx)
        .from(xxxx)
        .where(xxx);
    }
}

**Comment by soumyamishra12** [comment]
Hi Team,
Any update on this issue i am using oracle knex .16.3 version for the same getting same issue and project is dependent on this as will be using this frquesntly

**Comment by kibertoad** [comment]
@soumyamishra12 Could you please try 0.16.6-oracle-fix ? It has improved Oracle error handling quite a bit, I wonder if it addresses the specific problem that you are having.

**Comment by elhigu** [comment]
@soumyamishra12 this one https://github.com/tgriesser/knex/pull/2608 we are currently unable to run oracle tests so its a risky business to do changes there :(

**Comment by kibertoad** [comment]
@elhigu ahahaha, GMTA. Yeah, exactly for that reason I published it as a separate tag so that at least someone could test it.

**Comment by soumyamishra12** [comment]
@elhigu @kibertoad  have just changed it to 0.16.4 in my server and it's working correctly.Is it fixed for the version?

**Comment by kibertoad** [comment]
@soumyamishra12 Now that's interesting 😅. Must have been a side-effects for some of the fixes done there. Please let us know if it keeps being stable for you after a while.

**Comment by soumyamishra12** [comment]
@kibertoad Sure will observe for someday and let you know

**Comment by soumyamishra12** [comment]
@kibertoad I have tracked this issue but it's inconsistent, after 4 or 5 times calling it's again showing 3114 error. Please let me know if we can find a fix for this issue in some build

**Comment by kibertoad** [comment]
@soumyamishra12. Yes. Please try 0.16.6-oracle-fix

**Comment by soumyamishra12** [comment]
@kibertoad you mean to say 0.16.6 version?

**Comment by soumyamishra12** [comment]
I have deployed new change and took 0.16.6-oracle-fix  still the bug exists. It's not consistent enough after 1 or 2 hr interval if I try throws the error.

**Comment by elhigu** [comment]
@soumyamishra12 could you paste the error message? Are you sure it is the same one?

**Comment by oscarlnetoo** [comment]
Hello there,
@elhigu Any updates for this issue?

**Comment by icj217** [comment]
Running `0.16.6-oracle-fix` and it still does not recover from the ORA-03114 error. Here's the error/stack returned:
```
Error: ORA-03114: not connected to ORACLE\n
    at Connection.connection.executeAsync (/home/my-app/node_modules/knex/lib/dialects/oracledb/index.js:184:16)\n
    at /home/my-app/node_modules/knex/lib/dialects/oracledb/index.js:258:16\nFrom previous event:\n
    at Client_Oracledb._query (/home/my-app/node_modules/knex/lib/dialects/oracledb/index.js:250:10)\n
    at Client_Oracledb.query (/home/my-app/node_modules/knex/lib/client.js:202:17)\n
    at Runner.<anonymous> (/home/my-app/node_modules/knex/lib/runner.js:146:36)\nFrom previous event:\n
    at /home/my-app/node_modules/knex/lib/runner.js:48:21\n
    at runCallback (timers.js:705:18)\n
    at tryOnImmediate (timers.js:676:5)\nFrom previous event:\n
    at Runner.run (/home/my-app/node_modules/knex/lib/runner.js:34:31)\n
    at Builder.Target.then (/home/my-app/node_modules/knex/lib/interface.js:20:43)\n
    at my-appService.then [as getSummary] (/home/my-app/src/services/my-app.js:70:8)\n
    at getSummary (/home/my-app/src/routes/api/my-app.js:24:40)\n
    at handler (/home/my-app/src/routes/index.js:63:48)\n
    at Layer.handle [as handle_request] (/home/my-app/node_modules/express/lib/router/layer.js:95:5)\n
    at next (/home/my-app/node_modules/express/lib/router/route.js:137:13)\n
    at next (/home/my-app/src/services/validation.js:29:7)\n
    at handler (/home/my-app/src/routes/index.js:63:48)\n
    at Layer.handle [as handle_request] (/home/my-app/node_modules/express/lib/router/layer.js:95:5)\n
    at next (/home/my-app/node_modules/express/lib/router/route.js:137:13)\n
    at runner.then.errors (/home/my-app/node_modules/express-validator/check/check.js:16:7)
```

**Comment by icj217** [comment]
I've been able to implement a workaround for this issue for the time being using a Proxy wrapper. It relies upon on having a simple `db.js` module that establishes the knex object before exporting it and using it in other modules.

Basically, I'm using the `query-error` event to trigger a re-establishment of the connection and changing the value of the `myDb` variable. The Proxy is used to ensure that modules that have already imported `db` end up using the updated `myDb` instead of the statically exported one. Definitely not ideal but it seems to work.
```js
// db.js
import config from 'config'
import knex from 'knex'
import logger from './logger';

const myDbDbConfig = config.get('db.myDb')

// eslint-disable-next-line import/no-mutable-exports
let myDb = knex(myDbDbConfig)

myDb.on('query-error', (err) => {
  // Reconnect when we find a 3114 error (until knex issue #2608 is merged)
  if (err.message.indexOf(`ORA-03114`) > -1) {
    logger.error(`Encountered ORA-03114 database connection error. Automatically reconnecting.`)
    myDb = knex(myDbDbConfig)
  }
})

const handler = {
  // Uses the `myDb` variable in the module instead of exported instance which is static
  get: (_target, propKey) => (...args) => myDb[propKey].apply(this, args),
}

/*
  Using Proxy to allow us to intercept method calls and pass them
  through the `get` interceptor, which points them towards the non-exported
  `myDb` variable, which will reconnect automatically using the event listener

  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
  http://2ality.com/2015/10/intercepting-method-calls.html
*/
const db = new Proxy(myDb, handler)

export default db
```

And then in my other files:
```js
// other.js
import db from "./db";
// ...
return db.withSchema('foo').select('*')...
```

**Comment by elhigu** [comment]
Sounds like something in that implementation is failing... IIRC it was not merged because tests were missing...

**Comment by kibertoad** [comment]
@icj217 Can you try latest master?

**Comment by kibertoad** [comment]
@icj217 Just released 0.18.0-next2, would appreciate if you could give it a try and report back.

**Comment by icj217** [comment]
@kibertoad Just tested out `0.18.0-next2` and it seems to be working for me!

**Comment by kibertoad** [comment]
@soumyamishra12 It seems that updated fix is working; could you also try `0.18.0-next2`?

**Comment by elhigu** [comment]
Closing due to inactivity, might be fixed already.
