### ISSUE TITLE
master branch build broken: 'npm i knex/knex@master' does not work

### ISSUE THREAD

**Issue by xJonahS** [knex/knex#5184]
# Environment

Knex version: current master branch
OS: Windows

# Bug

1. Cant install from newer commits after Tag 2.0.0. Seems to be broken after dependerBot.

2. Error message

`npm i knex/knex#2.0.0`
![image](https://user-images.githubusercontent.com/58333113/168848297-e15ea37b-00ba-4e4b-aa87-32a5047b2880.png)
this works.

`npm i knex/knex#master`
![image](https://user-images.githubusercontent.com/58333113/168849417-eb350142-eeb3-4698-919f-c42c7728c696.png)
this does not work anymore.

I will try to update you, which commit is causing this issue. My first assumption is the dependerBot. Thanks in advance 👍

**Comment by kibertoad** [comment]
@code-ape Looks like some OS-dependent code ended up leaking into your PR after all. Could you take a look?

**Comment by kibertoad** [comment]
@xJonahS Fairly sure it's https://github.com/knex/knex/pull/5151

**Comment by code-ape** [comment]
@kibertoad cause was #5151 and is this single line in `package.json`. Intention was that when developers ran `npm install` while working on Knex it would automatically build the Typescript files. This was a mistake and it should be a husky for the git hook `post-checkout`. Will open a PR momentarily to fix.

https://github.com/knex/knex/blob/a4df3e35403756615f297ef75ac1d998035d65e6/package.json#L61

**Comment by code-ape** [comment]
Hey @xJonahS can you confirm that your issue with master is now resolved after my fix was merged? Thanks!

**Comment by xJonahS** [comment]
@code-ape Thanks for your fast response. The Issue does not seem to be resolved in my case. I get the same error message and you can see your new added husky command in the error message. Hope this helps in finding the issue!

![image](https://user-images.githubusercontent.com/58333113/168991819-1add40f6-aa8b-466e-8ff1-21f6cfe070df.png)

**Comment by code-ape** [comment]
1. @kibertoad please re-open 😞
2. Ok, @xJonahS, the PR #5184 did fix a lot of things but I apparently have massively underestimated the amount of magic that NPM does when installing from a git repo. I think have a fix and it "works for me" on an Ubuntu VM. Can you please try `npm install "code-ape/knex#test-git-install"` and report back if it works or not? If it does then I'll submit a PR to finally fix the last part of this!

**Comment by xJonahS** [comment]
@code-ape I tested the given npm install and i still get the same error message☹ (on Win10)

**Comment by code-ape** [comment]
Ok, I've got it working for Linux and MacOS and found why it's failing on Windows. Have to go do work stuff now but will get in a final fix this evening!

**Comment by xJonahS** [comment]
Thank you! Good luck with your work stuff 👍

**Comment by code-ape** [comment]
Ok, @xJonahS, I have pushed again to my branch and appeal to have fixed that final windows issue. There's now a CI test that verifies this. Can you try again with that same `npm install "code-ape/knex#test-git-install" --no-cache --verbose` and confirm?

**Comment by xJonahS** [comment]
@code-ape I can confirm that the install on windows is working again! 👍

**Comment by code-ape** [comment]
Thanks for working with me on this @xJonahS! That branch you tested has been merged into Knex master branch (https://github.com/knex/knex/commit/1baeefedf1debbba9537fccabbcf3b822de7e5b0) so your problem should now be resolved 😄

**Comment by OlivierCavadenti** [comment]
thanks @code-ape , so I close this one.
