### ISSUE TITLE
group by problems in union query

### ISSUE THREAD

**Issue by unsign3d** [knex/knex#913]
Hi all,
I need to perform 2 group by in the inner query of an union query

this is my code 

```
return bookshelf
        .knex('lists')
        // first half of the query, we just take
        // the list that the user is owner, we need to
        // have the field correctly
        .select('lists.id', 'lists.name', 'lists.public',
          'lists.editable', 'lists.owner_id', 'lists.created_at')
        .count('list_items.id as item_counter')
        .from('lists')
        .leftJoin('list_items', 'list.id', 'list_items.id')
        .where('lists.owner_id', user_id)
        .groupBy('list_members.list_id')
        // we just need to group by list_id
        //.groupBy('list_members.list_id')
        // second half of the query, we need to retrive
        // the list that the user is member, this works because
        // an admin is not a member
        .union(function(){
          this.select('lists.id', 'lists.name', 'lists.public',
            'lists.editable', 'lists.owner_id', 'lists.created_at')
          //.count('list_members.user_id as member_counter')
          .count('list_items.id as item_counter')
          .from('lists')
          .innerJoin('list_members', 'lists.id', 'list_members.list_id')
          .leftJoin('list_items', 'lists_id', 'lists_items.list_id')
          //.where('lists_members.user_id', user_id)
          .groupBy('list_members.list_id');
        });
```

the result query is

```
 select `lists`.`id`, `lists`.`name`, `lists`.`public`, `lists`.`editable`, `lists`.`owner_id`, `lists`.`created_at`, count(`list_items`.`id`) as `item_counter` from `lists` left join `list_items` on `list`.`id` = `list_items`.`id` where `lists`.`owner_id` = 1 union select `lists`.`id`, `lists`.`name`, `lists`.`public`, `lists`.`editable`, `lists`.`owner_id`, `lists`.`created_at`, count(`list_items`.`id`) as `item_counter` from `lists` inner join `list_members` on `lists`.`id` = `list_members`.`list_id` left join `list_items` on `lists_id` = `lists_items`.`list_id` group by `list_members`.`list_id` group by `list_members`.`list_id` - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group by `list_members`.`list_id`' at line 1
  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group by `list_members`.`list_id`' at line 1

```

the 2 group by are together in the last half of the query

**Comment by matthewsquire** [comment]
I've found that if you reorder the components in the compiler file to put group before union: Ie in lib/query/compiler.js go from

var components = ['columns', 'join', 'where', 'union', 'group', 'having', 'order', 'limit', 'offset', 'lock'];
to

var components = ['columns', 'join', 'where', 'group', 'union', 'having', 'order', 'limit', 'offset', 'lock'];

then the "group by" clauses get associated with the first & second part of the union correctly.  I'm not sure if this negatively impacts other dialects beyond mysql, but this change got me past this issue when using mysql.

**Comment by catmsred** [comment]
I had the same problem, and this fix worked for me too.  Will this be updated in the next release, or is there a solid reason for wanting group bys after the entire union in general?

**Comment by rustyraz** [comment]
Same thing here. Editing the lib file temporarily solves the problem. Thanks

**Comment by spruce-bruce** [comment]
Are people still modifying knex to make this work? This hasn't been addressed?

**Comment by catmsred** [comment]
I'm still editing the lib in every new release...

**Comment by spruce-bruce** [comment]
just looked at the file, https://github.com/tgriesser/knex/blob/0.11.10/src/query/compiler.js

That looks like everything's in the right order?

```
const components = [
  'columns', 'join', 'where', 'union', 'group',
  'having', 'order', 'limit', 'offset', 'lock'
];
```

**Comment by spruce-bruce** [comment]
oops - misread. Group goes BEFORE union.

**Comment by spruce-bruce** [comment]
So the issue is that because `'group', 'having',  'order', 'limit', 'offset', 'lock'` happen AFTER the union is processed we can never do a query like this:

```
select * from `table`
group by `some_field`
union
select * form `table`
```

same with using having, order, limit or offset in the first query. I don't know much about how knex works, but I suppose that the only reason a PR doesn't exist is because the above posters aren't sure about the ramifications of changing the order of the components array.

I've checked out the repo and I'm going to see if tests pass with the components order changed...

**Comment by mbsquid** [comment]
I haven’t run the tests from the repository but I changed the order on my app ~1yr ago and have been running fine in all query variations that I’ve tried.  
- Matt

**Comment by catmsred** [comment]
Like Matt, I have been running my app with the order switched for some time with no problems, but I appreciate @spruce-bruce taking the time to check our anecdotal evidence against the standard tests.  Thanks!

**Comment by spruce-bruce** [comment]
So I created a PR with the order changed, but it caused a failing test for MariaDB (makes sense)

https://github.com/tgriesser/knex/pull/1632

I know you guys are just moving union behind group, but order and limit are legitimate clauses in unions too so I tried that out. Since that doesn't work _really_ fixing union will take a greater understanding of the workings of knex than I have.

Unfortunately, it will be really hard for me to commit any more time to this, so I don't think I'll have a fix any time soon.

**Comment by catmsred** [comment]
@spruce-bruce Thank you for taking the time to look into it!

**Comment by wilsontgh** [comment]
I faced this problem to and one workaround that worked for me was this. From the above example by @spruce-bruce:
```
select * from `table`
group by `some_field`
union
select * form `table`
group by `some_other_field`
```

```
knex.from(function () {
   this.select('*').from('table').groupBy('some_field');
), true).union(function () {
   this.select('*').from('table').groupBy('some_other_field');
}, true).as('some_alias');
```
The `true` flag adds parentheses around the subquery. This also works for `.unionAll()`. Hope this helps!

**Comment by moll** [comment]
I believe the grouping bug is still the case with Knex v0.13.

**Comment by pmalouin** [comment]
I came here after encountering problems with combined `UNION ALL` and `ORDER BY`. Simply reordering the `components` array at https://github.com/tgriesser/knex/blob/0.13.0/src/query/compiler.js#L32 did not produce acceptable results.

Here is the code (inspired from the project's unit tests at https://github.com/tgriesser/knex/blob/0.13.0/test/unit/query/builder.js#L950):
```
var chain = qb().select('*').from('users').where('id', '=', 1).orderBy('id').limit(1).unionAll(function() {
  this.select('*').from('users').where('id', '=', 2);
});
```
Produces the following output right now:
```
select * from `users` where `id` = ? union all select * from `users` where `id` = ? order by `id` asc limit ?
```
Which is not right because I expected the `ORDER BY` and `LIMIT` clauses to apply to the first query.

After re-ordering the `components`, the `ORDER BY` and `LIMIT` clauses are at the right position:
```
select * from `users` where `id` = ? order by `id` asc limit ? union all select * from `users` where `id` = ?
```

Unfortunately, this query is still not valid at least for MySQL and PostgreSQL. As indicated in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/union.html), the queries need to be wrapped in parenthesis. The next step was to try the `wrap` argument to `.unionAll()`:
```
var chain = qb().select('*').from('users').where('id', '=', 1).orderBy('id').limit(1).unionAll(function() {
  this.select('*').from('users').where('id', '=', 2);
}, true);
```
and it produced the following result:
```
select * from `users` where `id` = ? order by `id` asc limit ? union all (select * from `users` where `id` = ?)
```
Which still has not an acceptable syntax because both the first and second queries need to be wrapped in parenthesis. So we might need to alter the behavior of the `wrap` argument to wrap both queries in order to use this feature.

Unfortunately, I had to fallback to raw queries for my needs. Here is a short code sample that combines an array of query builders together with UNION ALL statements between them:
```
const sqlExpressions = [];
let bindings = [];
queryBuilders.forEach(q => {
    const sql = q.toSQL();
    sqlExpressions.push('(' + sql.sql + ')');
    bindings = bindings.concat(sql.bindings);
});
const sql = sqlExpressions.join('UNION ALL');
return knex.raw(sql, bindings);
```

**Comment by elhigu** [comment]
@pmalouin knex also knows how to combine multiple query builders when they are passed as bindings to raw like this:

`knex.raw(queryBuilders.map(qb => '?').join('UNION ALL'), queryBuilders);`

**Comment by Raphyyy** [comment]
Hi,

```
knex.raw(queryBuilders.map(qb => '(?)').join('UNION ALL'), queryBuilders);
```

Still not acceptable according to the fact that limit and orderBy can't be added after the UNION. I have to add it on each query builder and so my data get sorted separately.

So right now with client Postgres I can't build this query with Knex, even with knex.raw() : 

```
select
      "id_sensor",
      avg(value) as value,
      time_bucket('15 minutes', datetime) AS datetime,
from
      a
where
      (
        "id_sensor" = '2250000003'
        or "id_group" = 64
      )
    and "datetime" >= '2018-07-19T18:10:00.000Z'
    and "datetime" <= '2018-07-20T18:10:00.000Z'
group by
    datetime, id_sensor
UNION ALL(
      select
        "id_sensor",
        "value",
        "datetime"
      from
        b
      where
        and "datetime" >= '2018-07-19T18:10:00.000Z'
        and "datetime" <= '2018-07-20T18:10:00.000Z'
)
order by
  "datetime" DESC
limit
  50000
```

Or if I am getting wrong, please show me the way

**Comment by elhigu** [comment]
@Raphyyy yeah that is tricky one, I cannot think any nice way to write it with knex.

**Comment by nicosierra** [comment]
@elhigu @Raphyyy I think there are spaces missing in your .join statement i.e. ` .join(' UNION ALL ')`

**Comment by Raphyyy** [comment]
This should not be closed

There is still no way to perform a query to retrieve data from 2 tables and perform an ORDER BY over all.

My case is pretty simple : I have 2 tables containing time series. One is for "prod" and the other one for "dev". They both have the same structure. I would like to perform a query to fetch datas from those 2 tables, like this : 

```
select
  id_sensor,
  value,
  datetime
from
  prod
where
    id_sensor = 123
UNION ALL (
  select
    id_sensor,
    value,
    datetime
  from
    dev
  where
    id_sensor = 123
)
order by
  time DESC
```

This case looks pretty simple, but knex can't build this query

**Comment by wubzz** [comment]
@Raphyyy Can't?

```javascript
const prod = knex('prod')
	.where({id_sensor: 123})
	.select([
		'id_sensor',
		'value',
		'datetime',
	]);

const dev = knex.raw(prod.clone().from('dev')).wrap('(', ')');

console.log(prod.unionAll(dev).orderBy('datetime', 'desc').toString())
```
> SELECT "id_sensor", "value", "datetime"
FROM "prod"
WHERE "id_sensor" = 123
UNION ALL
(SELECT "id_sensor", "value", "datetime" FROM "dev" WHERE "id_sensor" = 123)
ORDER BY "datetime" DESC

**Comment by Raphyyy** [comment]
@wubzz I am sorry this post is old, the query I would like to build is not the one I published yersterday, but the one I published last year :

```
select
  id_sensor,
  avg(value) as value,
  time_bucket('15 minutes', datetime) AS time
from
  a
where
  id_sensor = '123'
  and datetime >= '2018-07-19T18:10:00.000Z'
  and datetime <= '2018-07-20T18:10:00.000Z'
group by
  time, id_sensor
UNION ALL (
  select
    id_sensor,
    value,
    datetime as time
  from
    b
  where
    id_sensor = '123'
    and datetime >= '2018-07-19T18:10:00.000Z'
    and datetime <= '2018-07-20T18:10:00.000Z'
)
order by
  time DESC
```

The whole difference is that the first statement of the union use a `group by` and not on the second statement. The `order by` wrap the final query, not each statement.

```
const prod = knex('prod')
	.where({id_sensor: 123})
	.select([
		'id_sensor',
		'value',
		'datetime',
	]);

const dev = knex.raw(prod.clone().from('dev')).wrap('(', ')');

prod.groupBy('id_sensor', 'value', 'datetime');

console.log(prod.unionAll(dev).orderBy('datetime', 'desc').toString());
```

> select "id_sensor", "value", "datetime" from "prod" where "id_sensor" = 123 union all (select "id_sensor", "value", "datetime" from "dev" where "id_sensor" = 123) group by "id_sensor", "value", "datetime" order by "datetime" desc

The `group by` is attached to the the whole final query.

Sorry again for my misunderstood, my post is old and as a matter of fact, this issue is about `group by` in union query, not `order by`.

I did try to find a nice way to do this with knex but no clue, this is why I came on this issue thinking this could be an enhancement.
If there is a way or not gonna happen, then I'm stop posting here.

**Comment by sarneeh** [comment]
@unsign3d Why this issue has been closed?

**Comment by elhigu** [comment]
@sarneeh better to open new issue for the original post with proper reproduction + example what kind of query should be created if it is still a problem.

**Comment by regiszanandrea** [comment]
Hi, 

This problem still persist and I solved this creating a View on my PostgreSQL database doing the union on this view.

**Comment by karthikep** [comment]
For anyone who is struggling with this issue, here's my workaround,

1. Create a query that would return an empty set 
`
let query :Knex.QueryBuilder;
query.from('<tableA>').select('*').whereRaw('1 = 0');
`

2. Then, add the queries for the rest of the tables to this query using **unionAll** 
`
query.unionAll(function () {	
        query.from('<tableA>').select('*').where('<condition>').groupBy('<columnName>');
});
query.unionAll(function () {	
        query.from('<tableB>').select('*').where('<condition>').groupBy('<columnName>');
});`

This packages the groupBys with the their respective tables correctly instead of adding all the groupBys together at the end of the final query built.

**Comment by giovanni-bertoncelli** [comment]
This should not be closed @unsign3d . Is there any progress on this bug?

**Comment by erdinc** [comment]
any updates?

**Comment by kibertoad** [comment]
@OlivierCavadenti thoughts?

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti thoughts?

I will take a look this week to see what I can do

**Comment by OlivierCavadenti** [comment]
It seems the problem is due to the logic implementation of unions. 
The best option imo is, in the querybuilder, to affect each groupby (and having, etc.) statements to the right query part in the case of union clause is used.
Needs some rework btw.

**Comment by OlivierCavadenti** [comment]
> I came here after encountering problems with combined `UNION ALL` and `ORDER BY`. Simply reordering the `components` array at https://github.com/tgriesser/knex/blob/0.13.0/src/query/compiler.js#L32 did not produce acceptable results.
> 
> Here is the code (inspired from the project's unit tests at https://github.com/tgriesser/knex/blob/0.13.0/test/unit/query/builder.js#L950):
> 
> ```
> var chain = qb().select('*').from('users').where('id', '=', 1).orderBy('id').limit(1).unionAll(function() {
>   this.select('*').from('users').where('id', '=', 2);
> });
> ```
> 
> Produces the following output right now:
> 
> ```
> select * from `users` where `id` = ? union all select * from `users` where `id` = ? order by `id` asc limit ?
> ```
> 
> Which is not right because I expected the `ORDER BY` and `LIMIT` clauses to apply to the first query.
> 
> After re-ordering the `components`, the `ORDER BY` and `LIMIT` clauses are at the right position:
> 
> ```
> select * from `users` where `id` = ? order by `id` asc limit ? union all select * from `users` where `id` = ?
> ```
> 
> Unfortunately, this query is still not valid at least for MySQL and PostgreSQL. As indicated in the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/union.html), the queries need to be wrapped in parenthesis. The next step was to try the `wrap` argument to `.unionAll()`:
> 
> ```
> var chain = qb().select('*').from('users').where('id', '=', 1).orderBy('id').limit(1).unionAll(function() {
>   this.select('*').from('users').where('id', '=', 2);
> }, true);
> ```
> 
> and it produced the following result:
> 
> ```
> select * from `users` where `id` = ? order by `id` asc limit ? union all (select * from `users` where `id` = ?)
> ```
> 
> Which still has not an acceptable syntax because both the first and second queries need to be wrapped in parenthesis. So we might need to alter the behavior of the `wrap` argument to wrap both queries in order to use this feature.
> 
> Unfortunately, I had to fallback to raw queries for my needs. Here is a short code sample that combines an array of query builders together with UNION ALL statements between them:
> 
> ```
> const sqlExpressions = [];
> let bindings = [];
> queryBuilders.forEach(q => {
>     const sql = q.toSQL();
>     sqlExpressions.push('(' + sql.sql + ')');
>     bindings = bindings.concat(sql.bindings);
> });
> const sql = sqlExpressions.join('UNION ALL');
> return knex.raw(sql, bindings);
> ```

@pmalouin I push a PR but it's seems parenthesis with union statements are not a SQL standard and fail in a lot of dialects.
Seems be need to made subquery in each union if we want group by, order by, limit... to be applied in each union select.

https://stackoverflow.com/a/4653180/1535159

**Comment by thousandsofraccoons** [comment]
@OlivierCavadenti thank you, do you know when these changes will be released?

**Comment by kibertoad** [comment]
Today, when I'm back home :)

**Comment by kibertoad** [comment]
Released in 1.0.4
